def getError():
    # 错题本
    pass
